#!/bin/sh

export LD_LIBRARY_PATH=@PROJECT_BINARY_DIR@/target/classes:@PROJECT_BINARY_DIR@/target/test-classes:${LD_LIBRARY_PATH}:

java -cp .:../target/lib/*:../target/* ee.pub.lib.jni.Run $*

exit $?
