/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ee_pub_lib_jni_Example */

#ifndef _Included_ee_pub_lib_jni_Example
#define _Included_ee_pub_lib_jni_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ee_pub_lib_jni_Example
 * Method:    getHelloString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ee_pub_lib_jni_Example_getHelloString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
