/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_setmy_jni_example_Example */

#ifndef _Included_info_setmy_jni_example_Example
#define _Included_info_setmy_jni_example_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_setmy_jni_example_Example
 * Method:    getHelloString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_setmy_jni_example_Example_getHelloString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
